lines: [5-100, 5-200]   # 生产线列表

camera_inst: 2          # 子码流

camera_rotate: 3        # 不旋转  3 -> 不旋转, 0 -> 顺时针90度, 1 -> 顺时针180度, 2 -> 逆时针90度

python_path: C:/Users/yy/anaconda3/envs/py36/python.exe

#access_database_path: PinsCtrlData/Database/pins_ctrl_database.accdb
access_database_path: ../PinsCtrlData/Database/pins_ctrl_database.accdb

